/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package krcho.fbi.gui.dialogy;

import java.util.List;
import krcho.fbi.databaza.dao.CertifikatDao;
import krcho.fbi.databaza.dao.OdbornaPraxDao;
import krcho.fbi.databaza.dao.StupenVzdelaniaDao;
import krcho.fbi.databaza.dao.TypovaPoziciaDao;
import krcho.fbi.databaza.tabulky.Certifikat;
import krcho.fbi.databaza.tabulky.OdbornaPrax;
import krcho.fbi.databaza.tabulky.StupenVzdelania;
import krcho.fbi.databaza.tabulky.TypovaPozicia;
import krcho.fbi.gui.TextAreaFilter;
import krcho.fbi.gui.TextAreaKeyAdapter;
import krcho.fbi.hibernate.HibernateUtilities;
import org.hibernate.HibernateException;
import org.hibernate.Session;
import org.hibernate.Transaction;

/**
 *
 * @author Jozef Krcho
 */
public class HlavneInfoPozicieDialog extends javax.swing.JDialog {

    /**
     * Creates new form HlavneInfDialog
     */
    private TypovaPozicia pozicia;
    private boolean zmena;
    private java.awt.Frame parent;

    public HlavneInfoPozicieDialog(java.awt.Frame parent, boolean modal, TypovaPozicia pozicia) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.parent = parent;
        this.zmena = false;
        this.pozicia = pozicia;
        
        nazovPozicieTextArea.addKeyListener(new TextAreaKeyAdapter());
        nazovPozicieTextArea.setDocument(new TextAreaFilter(nazovPozicieTextArea, 100));
        charakteristikaTextArea.addKeyListener(new TextAreaKeyAdapter());
        
        Session session = HibernateUtilities.getSessionFactory().openSession();

        StupenVzdelaniaDao stupenVzdelaniaDao = new StupenVzdelaniaDao();
        stupenVzdelaniaDao.setSession(session);
        List<StupenVzdelania> stupneVzdelania = stupenVzdelaniaDao.findAll();
        for (StupenVzdelania stupen : stupneVzdelania) {
            stupenVzdelaniaComboBox.addItem(stupen);
        }

        OdbornaPraxDao odbornaPraxDao = new OdbornaPraxDao();
        odbornaPraxDao.setSession(session);
        List<OdbornaPrax> odbornePraxe = odbornaPraxDao.findAll();
        for (OdbornaPrax prax : odbornePraxe) {
            odbornaPraxComboBox.addItem(prax);
        }

        CertifikatDao certifikatDao = new CertifikatDao();
        certifikatDao.setSession(session);
        List<Certifikat> certifikaty = certifikatDao.findAll();
        for (Certifikat certifikat : certifikaty) {
            certifikatComboBox.addItem(certifikat);
        }

        nazovPozicieTextArea.setText(this.pozicia.getNazov());
        charakteristikaTextArea.setText(this.pozicia.getCharakteristika());
        if (this.pozicia.getOdbornaPrax() != null) {
            odbornaPraxComboBox.setSelectedItem(this.pozicia.getOdbornaPrax());
        }
        if (this.pozicia.getStupenVzdelania() != null) {
            stupenVzdelaniaComboBox.setSelectedItem(this.pozicia.getStupenVzdelania());
        }
        if (this.pozicia.getCertifikat() != null) {
            certifikatComboBox.setSelectedItem(this.pozicia.getCertifikat());
        }

        session.close();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        nazovPozicieLabel = new javax.swing.JLabel();
        charakteristikaLabel = new javax.swing.JLabel();
        stupenVzdelaniaLabel = new javax.swing.JLabel();
        odbornaPraxLabel = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        nazovPozicieTextArea = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        charakteristikaTextArea = new javax.swing.JTextArea();
        stupenVzdelaniaComboBox = new javax.swing.JComboBox<>();
        odbornaPraxComboBox = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        zrusitButton = new javax.swing.JButton();
        ulozitButton = new javax.swing.JButton();
        certifikatLabel = new javax.swing.JLabel();
        certifikatComboBox = new javax.swing.JComboBox<>();
        upravStupenVzdelaniaButton = new javax.swing.JButton();
        upravOdbornuPraxButton = new javax.swing.JButton();
        upravCertifikatButton = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Typová pozícia");
        setMinimumSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        nazovPozicieLabel.setText("Názov pozície:");
        getContentPane().add(nazovPozicieLabel, new java.awt.GridBagConstraints());

        charakteristikaLabel.setText("Charakteristika:");
        charakteristikaLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(charakteristikaLabel, gridBagConstraints);

        stupenVzdelaniaLabel.setText("Stupeň vzdelania:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(stupenVzdelaniaLabel, gridBagConstraints);

        odbornaPraxLabel.setText("Odborná prax:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(odbornaPraxLabel, gridBagConstraints);

        nazovPozicieTextArea.setBackground(new java.awt.Color(240, 240, 240));
        nazovPozicieTextArea.setColumns(20);
        nazovPozicieTextArea.setLineWrap(true);
        nazovPozicieTextArea.setRows(1);
        nazovPozicieTextArea.setWrapStyleWord(true);
        jScrollPane4.setViewportView(nazovPozicieTextArea);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jScrollPane4, gridBagConstraints);

        charakteristikaTextArea.setBackground(new java.awt.Color(240, 240, 240));
        charakteristikaTextArea.setColumns(20);
        charakteristikaTextArea.setLineWrap(true);
        charakteristikaTextArea.setRows(6);
        charakteristikaTextArea.setWrapStyleWord(true);
        jScrollPane5.setViewportView(charakteristikaTextArea);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jScrollPane5, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(stupenVzdelaniaComboBox, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(odbornaPraxComboBox, gridBagConstraints);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        zrusitButton.setText("Zrušiť");
        zrusitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zrusitButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(zrusitButton, gridBagConstraints);

        ulozitButton.setText("Uloziť");
        ulozitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ulozitButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel2.add(ulozitButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.SOUTHEAST;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jPanel2, gridBagConstraints);

        certifikatLabel.setText("Certifikát:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(certifikatLabel, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(certifikatComboBox, gridBagConstraints);

        upravStupenVzdelaniaButton.setText("Uprav");
        upravStupenVzdelaniaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upravStupenVzdelaniaButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(upravStupenVzdelaniaButton, gridBagConstraints);

        upravOdbornuPraxButton.setText("Uprav");
        upravOdbornuPraxButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upravOdbornuPraxButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(upravOdbornuPraxButton, gridBagConstraints);

        upravCertifikatButton.setText("Uprav");
        upravCertifikatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                upravCertifikatButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(upravCertifikatButton, gridBagConstraints);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 6;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(filler1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void zrusitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zrusitButtonActionPerformed
        zmena = false;
        this.dispose();
    }//GEN-LAST:event_zrusitButtonActionPerformed

    private void ulozitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ulozitButtonActionPerformed
        Session session = HibernateUtilities.getSessionFactory().openSession();
        Transaction transaction = session.beginTransaction();
        try {
            TypovaPoziciaDao poziciaDao = new TypovaPoziciaDao();
            poziciaDao.setSession(session);
            pozicia.setNazov(this.nazovPozicieTextArea.getText());
            pozicia.setCharakteristika(this.charakteristikaTextArea.getText());
            pozicia.setStupenVzdelania((StupenVzdelania) stupenVzdelaniaComboBox.getSelectedItem());
            pozicia.setOdbornaPrax((OdbornaPrax) odbornaPraxComboBox.getSelectedItem());
            pozicia.setCertifikat((Certifikat) certifikatComboBox.getSelectedItem());
            poziciaDao.save(pozicia);
            transaction.commit();
            zmena = true;
        } catch (HibernateException e) {
            e.printStackTrace();
            if (transaction != null) {
                transaction.rollback();
            }
        } finally {
            session.close();
        }
        this.dispose();
    }//GEN-LAST:event_ulozitButtonActionPerformed

    private void upravStupenVzdelaniaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upravStupenVzdelaniaButtonActionPerformed
        SpravcaTabulkyDialog dialog = new SpravcaTabulkyDialog(this, true, StupenVzdelania.class);
        dialog.setVisible(true);

        Session session = HibernateUtilities.getSessionFactory().openSession();
        StupenVzdelaniaDao stupenVzdelaniaDao = new StupenVzdelaniaDao();
        stupenVzdelaniaDao.setSession(session);
        List<StupenVzdelania> stupneVzdelania = stupenVzdelaniaDao.findAll();
        stupenVzdelaniaComboBox.removeAllItems();
        for (StupenVzdelania stupen : stupneVzdelania) {
            stupenVzdelaniaComboBox.addItem(stupen);
        }
        session.close();
    }//GEN-LAST:event_upravStupenVzdelaniaButtonActionPerformed

    private void upravCertifikatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upravCertifikatButtonActionPerformed
        SpravcaTabulkyDialog dialog = new SpravcaTabulkyDialog(this, true, Certifikat.class);
        dialog.setVisible(true);

        Session session = HibernateUtilities.getSessionFactory().openSession();
        CertifikatDao certifikatDao = new CertifikatDao();
        certifikatDao.setSession(session);
        List<Certifikat> certifikaty = certifikatDao.findAll();
        certifikatComboBox.removeAllItems();
        for (Certifikat certifikat : certifikaty) {
            certifikatComboBox.addItem(certifikat);
        }
        session.close();
    }//GEN-LAST:event_upravCertifikatButtonActionPerformed

    private void upravOdbornuPraxButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_upravOdbornuPraxButtonActionPerformed
        SpravcaTabulkyDialog dialog = new SpravcaTabulkyDialog(this, true, OdbornaPrax.class);
        dialog.setVisible(true);

        Session session = HibernateUtilities.getSessionFactory().openSession();
        OdbornaPraxDao odbornaPraxDao = new OdbornaPraxDao();
        odbornaPraxDao.setSession(session);
        List<OdbornaPrax> odbornePraxe = odbornaPraxDao.findAll();
        odbornaPraxComboBox.removeAllItems();
        for (OdbornaPrax odbornaPrax : odbornePraxe) {
            odbornaPraxComboBox.addItem(odbornaPrax);
        }
        session.close();
    }//GEN-LAST:event_upravOdbornuPraxButtonActionPerformed

    public boolean getZmena() {
        return zmena;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<Certifikat> certifikatComboBox;
    private javax.swing.JLabel certifikatLabel;
    private javax.swing.JLabel charakteristikaLabel;
    private javax.swing.JTextArea charakteristikaTextArea;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel nazovPozicieLabel;
    private javax.swing.JTextArea nazovPozicieTextArea;
    private javax.swing.JComboBox<OdbornaPrax> odbornaPraxComboBox;
    private javax.swing.JLabel odbornaPraxLabel;
    private javax.swing.JComboBox<StupenVzdelania> stupenVzdelaniaComboBox;
    private javax.swing.JLabel stupenVzdelaniaLabel;
    private javax.swing.JButton ulozitButton;
    private javax.swing.JButton upravCertifikatButton;
    private javax.swing.JButton upravOdbornuPraxButton;
    private javax.swing.JButton upravStupenVzdelaniaButton;
    private javax.swing.JButton zrusitButton;
    // End of variables declaration//GEN-END:variables
}
