/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package krcho.fbi.gui.dialogy;

import java.awt.Dialog;
import java.util.List;
import krcho.fbi.databaza.dao.NKRVedomostDao;
import krcho.fbi.databaza.dao.NKRZrucnostDao;
import krcho.fbi.databaza.tabulky.NKRVedomost;
import krcho.fbi.databaza.tabulky.NKRZrucnost;
import krcho.fbi.databaza.tabulky.enumy.Poziadavka;
import krcho.fbi.hibernate.HibernateUtilities;
import org.hibernate.Session;

/**
 *
 * @author Jozef Krcho
 */
public class PridajNutnaVyhodnaEkrDialog extends javax.swing.JDialog {

    /**
     * Creates new form VyberNutnaVyhodnaEkrDialog
     */
    private Class trieda;
    private boolean zmena;

    public PridajNutnaVyhodnaEkrDialog(Dialog owner, boolean modal, Class trieda) {
        super(owner, modal);
        initComponents();
        this.setLocationRelativeTo(null);

        this.trieda = trieda;
        this.zmena = false;

        switch (trieda.getSimpleName()) {
            case "OdbornaZrucnost":
                this.setTitle("Pridaj zručnosť");
                Session session1 = HibernateUtilities.getSessionFactory().openSession();
                NKRZrucnostDao nkrZrucnostDao = new NKRZrucnostDao();
                nkrZrucnostDao.setSession(session1);
                List<NKRZrucnost> urovneZrucnosti = nkrZrucnostDao.findAll();
                for (NKRZrucnost uroven : urovneZrucnosti) {
                    urovenComboBox.addItem(uroven);
                }
                session1.close();
                break;
            case "OdbornaVedomost":
                this.setTitle("Pridaj vedomosť");
                Session session2 = HibernateUtilities.getSessionFactory().openSession();
                NKRVedomostDao nkrVedomostDao = new NKRVedomostDao();
                nkrVedomostDao.setSession(session2);
                List<NKRVedomost> urovneVedomosti = nkrVedomostDao.findAll();
                for (NKRVedomost uroven : urovneVedomosti) {
                    urovenComboBox.addItem(uroven);
                }
                session2.close();
                break;
            case "Sposobilost":
                this.setTitle("Pridaj spôsobilosť");
                urovenComboBox.setVisible(false);
                jLabel1.setVisible(false);
                break;
            default:
                throw new AssertionError();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        nutnaRadioButton = new javax.swing.JRadioButton();
        vyhodnaRadioButton = new javax.swing.JRadioButton();
        urovenComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        pridajButton = new javax.swing.JButton();
        zrusButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        buttonGroup1.add(nutnaRadioButton);
        nutnaRadioButton.setSelected(true);
        nutnaRadioButton.setText("Nutná");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(nutnaRadioButton, gridBagConstraints);

        buttonGroup1.add(vyhodnaRadioButton);
        vyhodnaRadioButton.setText("Výhodná");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(vyhodnaRadioButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(urovenComboBox, gridBagConstraints);

        jLabel1.setText("NKR:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jLabel1, gridBagConstraints);

        jLabel2.setText("Podmienka:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jLabel2, gridBagConstraints);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        pridajButton.setText("Pridaj");
        pridajButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pridajButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(pridajButton, gridBagConstraints);

        zrusButton.setText("Zruš");
        zrusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zrusButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(zrusButton, gridBagConstraints);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(17, 0, 0, 0);
        getContentPane().add(jPanel1, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pridajButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pridajButtonActionPerformed
        this.zmena = true;
        this.dispose();
    }//GEN-LAST:event_pridajButtonActionPerformed

    private void zrusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zrusButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_zrusButtonActionPerformed

    public boolean isZmena() {
        return zmena;
    }

    public Poziadavka getPoziadavka() {
        if (nutnaRadioButton.isSelected()) {
            return Poziadavka.NUTNA;
        } else {
            return Poziadavka.VYHODNA;
        }
    }

    public Object getUroven() {
        return urovenComboBox.getSelectedItem();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton nutnaRadioButton;
    private javax.swing.JButton pridajButton;
    private javax.swing.JComboBox<Object> urovenComboBox;
    private javax.swing.JRadioButton vyhodnaRadioButton;
    private javax.swing.JButton zrusButton;
    // End of variables declaration//GEN-END:variables
}
