/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package krcho.fbi.gui.dialogy;

import krcho.fbi.databaza.tabulky.TypObjektu;
import krcho.fbi.databaza.tabulky.VnutorneBR;
import krcho.fbi.databaza.tabulky.VonkajsieBR;
import krcho.fbi.gui.tablemodel.RizikaObjektuModel;
import krcho.fbi.gui.tablemodel.VnutorneBRModel;
import krcho.fbi.gui.tablemodel.VonkajsieBRModel;

/**
 *
 * @author Jozef Krcho
 */
public class RizikaObjektuDialog extends javax.swing.JDialog {

    /**
     * Creates new form RizikaObjektuDialog
     */
    private static final int SIRKA_ID = 60;
    private TypObjektu typObjektu;

    public RizikaObjektuDialog(java.awt.Frame parent, boolean modal, TypObjektu typObjektu) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        this.typObjektu = typObjektu;

        rizikaObjektuTable.setModel(new RizikaObjektuModel(typObjektu));
        rizikaObjektuTable.getColumn("Id").setMaxWidth(SIRKA_ID);
        vnutorneBezRizikaTable.setModel(new VnutorneBRModel());
        vnutorneBezRizikaTable.getColumn("Id").setMaxWidth(SIRKA_ID);
        vonkajsieBezRizikaTable.setModel(new VonkajsieBRModel());
        vonkajsieBezRizikaTable.getColumn("Id").setMaxWidth(SIRKA_ID);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jTabbedPane1 = new javax.swing.JTabbedPane();
        vonkajsieBRPanel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        vonkajsieBezRizikaTable = new javax.swing.JTable();
        vnutorneBRPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        vnutorneBezRizikaTable = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        rizikaObjektuTable = new javax.swing.JTable();
        pridatButton = new javax.swing.JButton();
        odobratButton = new javax.swing.JButton();
        hotovoButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Riziká objektu");
        setMinimumSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jTabbedPane1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(50, 50));

        vonkajsieBRPanel.setLayout(new java.awt.GridBagLayout());

        vonkajsieBezRizikaTable.setModel(new VonkajsieBRModel());
        vonkajsieBezRizikaTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane4.setViewportView(vonkajsieBezRizikaTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        vonkajsieBRPanel.add(jScrollPane4, gridBagConstraints);

        jTabbedPane1.addTab("Vonkajšie", vonkajsieBRPanel);

        vnutorneBRPanel.setLayout(new java.awt.GridBagLayout());

        vnutorneBezRizikaTable.setModel(new VnutorneBRModel());
        vnutorneBezRizikaTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane3.setViewportView(vnutorneBezRizikaTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        vnutorneBRPanel.add(jScrollPane3, gridBagConstraints);

        jTabbedPane1.addTab("Vnútorné", vnutorneBRPanel);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jTabbedPane1, gridBagConstraints);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(50, 50));

        rizikaObjektuTable.setModel(new RizikaObjektuModel());
        rizikaObjektuTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(rizikaObjektuTable);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 0.5;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        pridatButton.setText("Pridať");
        pridatButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pridatButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(50, 5, 5, 5);
        getContentPane().add(pridatButton, gridBagConstraints);

        odobratButton.setText("Odobrať");
        odobratButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                odobratButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(odobratButton, gridBagConstraints);

        hotovoButton.setText("Hotovo");
        hotovoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotovoButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(hotovoButton, gridBagConstraints);

        jLabel1.setText("Bezpečnostné riziká");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jLabel1, gridBagConstraints);

        jLabel2.setText("Riziká objektu");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        getContentPane().add(jLabel2, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void hotovoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotovoButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_hotovoButtonActionPerformed

    private void pridatButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pridatButtonActionPerformed
        int vybranyRiadok = -1;
        if (jTabbedPane1.getSelectedIndex() == 0) {
            vybranyRiadok = vonkajsieBezRizikaTable.getSelectedRow();
            if (vybranyRiadok >= 0) {
                VonkajsieBRModel vonkajsieBRModel = (VonkajsieBRModel) vonkajsieBezRizikaTable.getModel();
                VonkajsieBR vonkajsieBR = vonkajsieBRModel.getVonkajsieBezRiziko(vybranyRiadok);
                RizikaObjektuModel rizikaObjektuModel = (RizikaObjektuModel) rizikaObjektuTable.getModel();
                rizikaObjektuModel.vlozVonkajsieRizikoObjektu(vonkajsieBR);
            }
        } else if (jTabbedPane1.getSelectedIndex() == 1) {
            vybranyRiadok = vnutorneBezRizikaTable.getSelectedRow();
            if (vybranyRiadok >= 0) {
                VnutorneBRModel vnutorneBRModel = (VnutorneBRModel) vnutorneBezRizikaTable.getModel();
                VnutorneBR vnutorneBR = vnutorneBRModel.getVnutorneBezRiziko(vybranyRiadok);
                RizikaObjektuModel rizikaObjektuModel = (RizikaObjektuModel) rizikaObjektuTable.getModel();
                rizikaObjektuModel.vlozVnutorneRizikoObjektu(vnutorneBR);
            }
        }
    }//GEN-LAST:event_pridatButtonActionPerformed

    private void odobratButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_odobratButtonActionPerformed
        int vybranyRiadok = rizikaObjektuTable.getSelectedRow();
        if (vybranyRiadok >= 0) {
            RizikaObjektuModel rizikaObjektuModel = (RizikaObjektuModel) rizikaObjektuTable.getModel();
            rizikaObjektuModel.vymazRizikoObjektu(vybranyRiadok);
        }
    }//GEN-LAST:event_odobratButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton hotovoButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton odobratButton;
    private javax.swing.JButton pridatButton;
    private javax.swing.JTable rizikaObjektuTable;
    private javax.swing.JPanel vnutorneBRPanel;
    private javax.swing.JTable vnutorneBezRizikaTable;
    private javax.swing.JPanel vonkajsieBRPanel;
    private javax.swing.JTable vonkajsieBezRizikaTable;
    // End of variables declaration//GEN-END:variables
}
